version: 2.1

orbs:
  android: circleci/android@2.3.0

machines:
  android: &android
    executor:
      name: android/android-docker
      resource-class: large
      tag: 2023.11.1

commands:
  gradle:
    parameters:
      title:
        type: string
      task:
        type: string
    steps:
      - run:
          name: <<parameters.title>>
          command: |
            ./gradlew <<parameters.task>> --no-daemon
  switch-comparison-branch:
    parameters:
      branch:
        type: string
        default: '$(curl -s -H "Authorization: token ${GITHUB_TOKEN}" $(echo https://api.github.com/repos/${CIRCLE_PULL_REQUEST:19} | sed "s/\/pull\//\/pulls\//") | jq ".base.ref" | tr -d "\042" )'
    steps:
      - run:
          # FIXME: make it work ;;
          name: Switch to comparison branch
          command: |
            git fetch origin <<parameters.branch>>
            PARENT_BRANCH=$(git log --oneline origin/<<parameters.branch>>)
            git merge-base origin/<<parameters.branch>> $PARENT_BRANCH
            git checkout -b <<parameters.branch>> origin/<<parameters.branch>>-comparison

jobs:
  record:
    <<: *android
    steps:
      # TODO: check mode;
      - checkout
      - switch-comparison-branch
      - gradle:
          title: Record screenshots
          task: recordRoborazziDebug
      # TODO: push comparison branch
  compare:
    <<: *android
    steps:
      - checkout
      # TODO: import screenshots from comparison branch
      - gradle:
          title: Compare screenshots
          task: compareRoborazziDebug

workflows:
  ci:
    jobs:
      # TODO: when pull request is opened
      - record:
          filters:
            branches:
              only:
                - main
                - /feature\/.*/
      - compare:
          requires:
            - record
          filters:
            branches:
              only:
                - main
                - /feature\/.*/
      # TODO: clear old comment and write new comment on PR with compare results
      # TODO: when comparison branch's base branch(parent of the pull request) is merged or closed, delete comparison branch