version: 2.1

orbs:
  android: circleci/android@2.3.0

machines:
  android: &android
    executor:
      name: android/android-docker
      resource-class: large
      tag: 2023.11.1

commands:
  gradle:
    parameters:
      title:
        type: string
      task:
        type: string
    steps:
      - run:
          name: <<parameters.title>>
          command: |
            ./gradlew <<parameters.task>> --no-daemon

jobs:
  record:
    <<: *android
    steps:
      # TODO: check mode;
      # TODO: check if comparison branch exists, if not, create it.
      # FIXME: checkout to comparison branch.
      - checkout
      - gradle:
          title: Record screenshots
          task: recordRoborazziDebug
  compare:
    <<: *android
    steps:
      # FIXME: checkout to target branch
      - checkout
      # TODO: import screenshots from comparison branch
      - gradle:
          title: Compare screenshots
          task: compareRoborazziDebug

workflows:
  ci:
    jobs:
      # TODO: when pull request is opened
      - record:
          filters:
            branches:
              only:
                - main
                - /feature\/.*/
      - compare:
          requires:
            - record
          filters:
            branches:
              only:
                - main
                - /feature\/.*/
      # TODO: clear old comment and write new comment on PR with compare results
      # TODO: when pull request is merged or closed, delete comparison branch