version: 2.1

orbs:
  android: circleci/android@2.3.0
  gh: circleci/github-cli@2.3.0

machines:
  android: &android
    executor:
      name: android/android-docker
      resource-class: large
      tag: 2023.11.1

commands:
  gradle:
    parameters:
      title:
        type: string
      task:
        type: string
    steps:
      - run:
          name: <<parameters.title>>
          command: |
            ./gradlew <<parameters.task>> --no-daemon

  switch-comparison-branch:
    steps:
      - run:
          # FIXME: make it work ;;
          name: Switch to comparison branch
          command: |
            git fetch origin $CIRCLE_BRANCH
            PARENT_BRANCH=$(git show-branch | grep '*' | grep -v "$(git rev-parse --abbrev-ref HEAD)" | head -n1 | sed 's/.*\[\(.*\)\].*/\1/' | sed 's/[\^~].*//')
            echo "Parent branch: $PARENT_BRANCH"
            BASE_COMMIT=$(git merge-base $PARENT_BRANCH $CIRCLE_BRANCH)
            echo "Base commit hash: $BASE_COMMIT"
            git reset --hard $BASE_COMMIT
            git checkout -b comparison-$CIRCLE_BRANCH
            echo "Switched to comparison branch: comparison-$CIRCLE_BRANCH"

  find_and_store_artifacts:
    parameters:
      path:
        type: string
    steps:
      - run:
          name: Find and merge roborazzi folders
          command: |
            mkdir -p $CIRCLE_BRANCH/merged/<<parameters.path>>
            find . -type d -path "./<<parameters.path>>/*" -exec cp -r {} $CIRCLE_BRANCH/merged/<<parameters.path>> \;
      - store_artifacts:
          path: $CIRCLE_BRANCH/merged/<<parameters.path>>

jobs:
  import_artifacts:
    <<: *android
    steps:
      # TODO: check mode
      - checkout
      # TODO: check artifacts
      # TODO: if artifacts exist, import them and finish the job
      # TODO: else,
      - switch-comparison-branch
      - gradle:
          title: Record target branch screenshots
          task: recordRoborazziDebug
      # TODO: export artifacts
      # TODO: checkout to the original branch
      # TODO: import artifacts
  unit_test:
    <<: *android
    steps:
      - gradle:
          title: Compare screenshots
          task: compareRoborazziDebug
  export_artifacts:
    <<: *android
    steps:
      - find_and_store_artifacts:
          path: app/build/outputs/roborazzi
      - find_and_store_artifacts:
          path: app/build/reports
      - find_and_store_artifacts:
          path: app/build/test-results

workflows:
  ci:
    jobs:
      - import_artifacts:
          filters:
            branches:
              only:
                - main
                - /feature\/.*/
      - unit_test:
          requires:
            - import_artifacts
          filters:
            branches:
              only:
                - main
                - /feature\/.*/
      - export_artifacts:
          requires:
            - unit_test
          filters:
            branches:
              only:
                - main
                - /feature\/.*/
        # TODO: clear old comment and write new comment on PR
        # TODO: when comparison branch's base branch(parent of the pull request) is merged or closed, delete comparison branch